# Generated by Django 2.2.14 on 2023-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-09-05'),
            preserve_default=False,
        ),
    ]
